Repository TheOdinProject/css-exercises, pull requests merged in 2022-08, with the labels that each got.

#207 04-flex-information: Add missing question mark to html files
  flex/04-flex-information/desired-outcome.png
  flex/04-flex-information/index.html
  flex/04-flex-information/solution/solution.html
Labels: Status: Under Review, Type: Easy Fix

#209 06-cascade-fix: Add missing weight from solution.css
  foundations/06-cascade-fix/style.css
Labels: Status: Under Review

#211 Foundations/06-cascade-fix: Update solution comments
  foundations/06-cascade-fix/solution/solution.css
Labels: Status: Needs Review, Type: Easy Fix
