Repository TheOdinProject/css-exercises, pull requests merged in 2022-02, with the labels that each got.

#129 Fixed typo in grid-layout-2 exercise
  grid/02-grid-layout-2/README.md
Labels: Type: Documentation, Status: Accepted

#117 Templates/guides: Create and update files
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: Type: Documentation

#110 Fix issue for users with color blindness
  foundations/06-cascade-fix/README.md
  foundations/06-cascade-fix/desired-outcome.png
  foundations/06-cascade-fix/index.html
  foundations/06-cascade-fix/solution/solution.css
  foundations/06-cascade-fix/solution/solution.html
  foundations/06-cascade-fix/style.css
Labels: Type: Enhancement, Type: Accessibility

#142 CSS Grid Exercise 03-grid-layout-3: Amend README
  grid/03-grid-layout-3/README.md
Labels: Status: Under Review, Type: Easy Fix

#144 04-flex-information: Remove extra semicolon in solution.css
  flex/04-flex-information/solution/solution.css
Labels: Status: Under Review, Type: Easy Fix
