Repository TheOdinProject/css-exercises, pull requests merged in 2022-07, with the labels that each got.

#187 grid/03-grid-layout-3/solution/solution.css : the grid-template-row command seems unnecessary
  grid/03-grid-layout-3/solution/solution.css
Labels: Status: Under Review

#202 Flex and Foundations: add alt text for accessibility (#201)
  flex/06-flex-layout/index.html
  flex/06-flex-layout/solution/solution.html
  foundations/04-chaining-selectors/index.html
  foundations/04-chaining-selectors/solution/solution.html
Labels: Type: Accessibility, Status: Under Review

#205 Cascade-fix: update for accessibility #188
  foundations/06-cascade-fix/README.md
  foundations/06-cascade-fix/desired-outcome.png
  foundations/06-cascade-fix/index.html
  foundations/06-cascade-fix/solution/solution.css
  foundations/06-cascade-fix/solution/solution.html
  foundations/06-cascade-fix/style.css
Labels: Type: Enhancement, Type: Accessibility, Status: Under Review
